### ISSUE TITLE
Running on Ubuntu. Got error 'exec: "mumax3": executable file not found in $PATH'

### ISSUE THREAD

**Issue by gabrielwu84** [mumax/mumax.github.io#1]
Hi, 

I would like to check if the program has been tested on Ubuntu - I got the following issue when I try to run it with a .mx3 config file in the same directory:

> exec: "mumax3": executable file not found in $PATH 

I wish to find out if it is a mistake that I am making. 

Many thanks, 
Gabriel

**Comment by gabrielwu84** [comment]
Hi, I found that the error message went away after I copied the file to one of the locations in $PATH. 

However, I have since encountered the error that I cannot solve the same way:

> mumax3-cuda6.0: error while loading shared libraries: libcufft.so.6.0: cannot open shared object file: No such file or directory exit status 127 

Just like to ask if there is a procedure for installing this on Ubuntu.

Many thanks, 
Gabriel

**Comment by barnex** [comment]
Hi Gabriel,
please post any mumax related questions here:
https://groups.google.com/forum/#!forum/mumax2
-Arne.
